export default {
    userid:'userid',
    email:'email',
    mobile:'mobile',
    name:'name',
    last_name:'last_name',
    pincode:'pincode',
    area:'area',
    address:'address',
    gender:'gender',
    dob:'dob',
    
    roundname:'roundname',
    commonQuizId:'commonQuizId',
    Token:'Token',
    correctCount:'correctCount',
    taken_time:'taken_time',
    total_attempts:'total_attempts',
    attempArrat:'attempArrat',
}